# Generated by Django 3.2 on 2024-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='payment_terms',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('cloud', 'Cloud Services'), ('data_analytics', 'Data Analytics'), ('cyber_security', 'Cyber Security'), ('networking', 'Networking'), ('it_support', 'IT Support'), ('ai_ml', 'AI & Machine Learning'), ('devops', 'DevOps'), ('consulting', 'Consulting')], max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_package',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=100),
        ),
    ]
