# Generated by Django 3.2 on 2024-07-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20240722_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_address',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
