# Generated by Django 3.2 on 2024-07-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20240724_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_address',
        ),
    ]
