# Generated by Django 3.2 on 2024-07-24 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_subscription_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
