# Generated by Django 3.2 on 2024-07-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_subscription_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
