# Generated by Django 3.2 on 2024-07-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_delete_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
